#!/usr/bin/env bash
# Prepares everything the plugin's PHPUnit tests need:
# the WordPress test suite matching the installed core, PHPUnit, the polyfills,
# a wp-tests-config.php and an empty test database.
#
# Safe to run repeatedly - existing downloads are reused.
set -euo pipefail

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/env.sh"

mkdir -p "$CACHE"

if [ ! -f "$WP_ROOT/wp-includes/version.php" ]; then
	echo "No WordPress install found at $WP_ROOT" >&2
	exit 1
fi

# The folder name says 6.3, but the install gets updated in place, so ask core.
WP_VERSION="$( "$PHP" -r 'require $argv[1]; echo $wp_version;' "$WP_ROOT/wp-includes/version.php" )"
TAG="${CPW_WP_VERSION:-$WP_VERSION}"

# 1. WordPress test suite, matching the installed core version.
STAMP="$CACHE/wp-tests/.version"
if [ ! -f "$STAMP" ] || [ "$( cat "$STAMP" )" != "$TAG" ]; then
	echo "Fetching the WordPress $TAG test suite ..."
	command -v svn >/dev/null || { echo "svn is required to fetch the test suite." >&2; exit 1; }
	rm -rf "$CACHE/wp-tests/tests"
	mkdir -p "$CACHE/wp-tests/tests"
	svn export -q "https://develop.svn.wordpress.org/tags/$TAG/tests/phpunit" "$CACHE/wp-tests/tests/phpunit"
	echo "$TAG" > "$STAMP"
fi

# 2. PHPUnit.
PHPUNIT_PHAR="$CACHE/phpunit-$PHPUNIT_VERSION.phar"
if [ ! -f "$PHPUNIT_PHAR" ]; then
	echo "Fetching PHPUnit $PHPUNIT_VERSION ..."
	curl -sSL -o "$PHPUNIT_PHAR" "https://phar.phpunit.de/phpunit-$PHPUNIT_VERSION.phar"
fi

# 3. Yoast PHPUnit polyfills, required by the WordPress test suite.
if [ ! -f "$CACHE/PHPUnit-Polyfills-$POLYFILLS_VERSION/phpunitpolyfills-autoload.php" ]; then
	echo "Fetching PHPUnit Polyfills $POLYFILLS_VERSION ..."
	curl -sSL -o "$CACHE/polyfills.tar.gz" \
		"https://github.com/Yoast/PHPUnit-Polyfills/archive/refs/tags/$POLYFILLS_VERSION.tar.gz"
	tar xzf "$CACHE/polyfills.tar.gz" -C "$CACHE"
	rm -f "$CACHE/polyfills.tar.gz"
fi

# 4. Config for the test suite. Rewritten every run so path changes are picked up.
cat > "$CACHE/wp-tests/wp-tests-config.php" <<PHP
<?php
// Generated by tests/local/setup.sh - do not edit, your changes will be overwritten.
define( 'ABSPATH', '$WP_ROOT/' );
define( 'WP_DEFAULT_THEME', 'default' );

define( 'DB_NAME', '$DB_NAME' );
define( 'DB_USER', '$DB_USER' );
define( 'DB_PASSWORD', '$DB_PASSWORD' );
define( 'DB_HOST', '$DB_HOST' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

define( 'AUTH_KEY', 'cpw tests key 1' );
define( 'SECURE_AUTH_KEY', 'cpw tests key 2' );
define( 'LOGGED_IN_KEY', 'cpw tests key 3' );
define( 'NONCE_KEY', 'cpw tests key 4' );
define( 'AUTH_SALT', 'cpw tests salt 1' );
define( 'SECURE_AUTH_SALT', 'cpw tests salt 2' );
define( 'LOGGED_IN_SALT', 'cpw tests salt 3' );
define( 'NONCE_SALT', 'cpw tests salt 4' );

\$table_prefix = 'wptests_';

define( 'WP_TESTS_DOMAIN', 'example.org' );
define( 'WP_TESTS_EMAIL', 'admin@example.org' );
define( 'WP_TESTS_TITLE', 'Test Blog' );

define( 'WP_PHP_BINARY', '$PHP' );
define( 'WPLANG', '' );
PHP

# 5. The test database. The suite drops and recreates all wptests_ tables in it.
"$PHP" -r '
$mysqli = @new mysqli( $argv[1], $argv[2], $argv[3] );
if ( $mysqli->connect_errno ) {
	fwrite( STDERR, "Cannot reach the database at {$argv[1]} as {$argv[2]}: {$mysqli->connect_error}\n" );
	fwrite( STDERR, "Is the MySQL server running? Override with CPW_DB_HOST / CPW_DB_USER / CPW_DB_PASSWORD.\n" );
	exit( 1 );
}
$name = str_replace( "`", "", $argv[4] );
if ( ! $mysqli->query( "CREATE DATABASE IF NOT EXISTS `$name` DEFAULT CHARACTER SET utf8mb4" ) ) {
	fwrite( STDERR, "Could not create the database $name: {$mysqli->error}\n" );
	exit( 1 );
}
' "$DB_HOST" "$DB_USER" "$DB_PASSWORD" "$DB_NAME"

echo "Ready: WordPress $TAG test suite, PHP $( "$PHP" -r 'echo PHP_VERSION;' ), database $DB_NAME."
